//mutions-user
export const GET_USER_INFO_MUTIONS = "GET_USER_INFO_MUTIONS";
export const GET_USER_BIND_INFO_MUTIONS = "GET_USER_BIND_INFO_MUTIONS";
export const GET_OTC_USER_INFO_MUTIONS = "GET_OTC_USER_INFO_MUTIONS";
export const GET_CURRENT_USER_INFO_MUTIONS = "GET_CURRENT_USER_INFO_MUTIONS";
export const GET_KYC_USER_INFO_MUTIONS = "GET_KYC_USER_INFO_MUTIONS";
export const GET_KYC_STATUS_MUTIONS = "GET_KYC_STATUS_MUTIONS";
export const GET_NICKNAME_MUTIONS = "GET_NICKNAME_MUTIONS";
//mutions-upload
export const SET_UPLOAD_MUTIONS = "SET_UPLOAD_MUTIONS";
export const GET_UPLOAD_URL_MUTIONS = "GET_UPLOAD_URL_MUTIONS";
//mutions-pay-method
export const GET_PAY_TYPE_MUTIONS = "GET_PAY_TYPE_MUTIONS";
export const GET_PAY_LIST_MUTIONS = "GET_PAY_LIST_MUTIONS";
export const UPDATE_PAY_METHOD_MUTIONS = "UPDATE_PAY_METHOD_MUTIONS";
export const ADD_PAY_METHOD_MUTIONS = "ADD_PAY_METHOD_MUTIONS";
export const DELETE_PAY_METHOD_MUTIONS = "DELETE__PAY_METHOD_MUTIONS";
//mutions-defriend
export const GET_DEFRIEND_LIST_MUTIONS = "GET_DEFRIEND_LIST_MUTIONS";
export const ADD_DEFRIEND_MUTIONS = "ADD_DEFRIEND_MUTIONS";
export const REMOVE_DEFRIEND_MUTIONS = "REMOVE_DEFRIEND_MUTIONS";
export const CHECK_DEFRIEND_MUTIONS = "CHECK_DEFRIEND_MUTIONS";

//actions-user
export const USER_LOGIN_OUT_ACTIONS = "USER_LOGIN_OUT_ACTIONS";
export const GET_USER_INFO_ACTIONS = "GET_USER_INFO_ACTIONS";
export const GET_USER_BIND_INFO_ACTIONS = "GET_USER_BIND_INFO_ACTIONS";
export const GET_OTC_USER_INFO_ACTIONS = "GET_OTC_USER_INFO_ACTIONS";
export const GET_CURRENT_USER_INFO_ACTIONS = "GET_CURRENT_USER_INFO_ACTIONS";
export const GET_KYC_USER_INFO_ACTIONS = "GET_KYC_USER_INFO_ACTIONS";
export const GET_KYC_STATUS_ACTIONS = "GET_KYC_STATUS_ACTIONS";
export const SET_NICKNAME_ACTIONS = "SET_NICKNAME_ACTIONS";
export const GET_NICKNAME_ACTIONS = "GET_NICKNAME_ACTIONS";
//actions-upload
export const SET_UPLOAD_ACTIONS = "SET_UPLOAD_ACTIONS";
export const GET_UPLOAD_URL_ACTIONS = "GET_UPLOAD_URL_ACTIONS";
//actions-pay-method
export const VERIFY_SECERT_ACTIONS = "VERIFY_SECERT_ACTIONS";
export const GET_PAY_TYPE_ACTIONS = "GET_PAY_TYPE_ACTIONS";
export const GET_PAY_LIST_ACTIONS = "GET_PAY_LIST_ACTIONS";
export const UPDATE_PAY_METHOD_ACTIONS = "UPDATE_PAY_METHOD_ACTIONS";
export const ADD_PAY_METHOD_ACTIONS = "ADD_PAY_METHOD_ACTIONS";
export const DELETE_PAY_METHOD_ACTIONS = "DELETE__PAY_METHOD_ACTIONS";
//actions-defriend
export const GET_DEFRIEND_LIST_ACTIONS = "GET_DEFRIEND_LIST";
export const ADD_DEFRIEND_ACTIONS = "ADD_DEFRIEND_ACTIONS";
export const REMOVE_DEFRIEND_ACTIONS = "REMOVE_DEFRIEND_ACTIONS";
export const CHECK_DEFRIEND_ACTIONS = "CHECK_DEFRIEND_ACTIONS";
