export const GET_TRADE_ASSET_LIST_MUTIONS = 'GET_TRADE_ASSET_LIST_MUTIONS';
export const GET_TRADE_ASSET_ALL_MUTIONS = 'GET_TRADE_ASSET_ALL_MUTIONS';
export const GET_TRADE_ASSET_TRANSFER_MUTIONS = 'GET_TRADE_ASSET_TRANSFER_MUTIONS';
export const GET_TRADE_ASSET_DEPOSIT_MUTIONS = 'GET_TRADE_ASSET_DEPOSIT_MUTIONS';

export const GET_TRADE_ASSET_LIST_ACTIONS = 'GET_TRADE_ASSET_LIST_ACTIONS';
export const GET_TRADE_ASSET_ALL_ACTIONS = 'GET_TRADE_ASSET_ALL_ACTIONS';
export const TRADE_ASSET_TRANSFER_ACTIONS = 'TRADE_ASSET_TRANSFER_ACTIONS';
export const TRADE_ASSET_DEPOSIT_ACTIONS = 'TRADE_ASSET_DEPOSIT_ACTIONS';

export const USER_BUSINESS_ASK_ACTIONS = 'user/businessAsk';
export const USER_BUSSINESS_CANCEL_ACTIONS = 'USER_BUSSINESS_CANCEL_ACTIONS';
export const USER_BUSINESS_INFO_ACTIONS = 'user/getbusinessInfo';
export const USER_BUSINESS_INFO_MUTIONS = 'user/setbusinessInfo';
export const USER_BUSINESS_BUSIPROMOTION_ACTIONS = 'user/business/busiPromotion';
